## Почему мы должны использовать NumPy?

**Эффективная работа с массивами и матрицами:**

NumPy предоставляет высокопроизводительные структуры данных для хранения и манипулирования массивами и матрицами, что существенно ускоряет вычисления.

**Возможности для научных вычислений:**

Эта библиотека содержат широкий набор функций и методов для решения разнообразных задач, таких как оптимизация, аппроксимация данных, решение дифференциальных уравнений, интегрирование и многое другое.

**Удобство и простота в использовании:**

Библиотека предлагает простой и интуитивно понятный синтаксис, что облегчает разработку и улучшает читаемость кода.

## NumPy

Простое напоминание из лекции:

    Создание массивов:
        np.array(iterable): Создает одномерный массив из итерируемого объекта.
        np.zeros(shape): Создает массив из нулей заданной формы.
        np.ones(shape): Создает массив из единиц заданной формы.
        np.empty(shape): Создает массив без инициализации заданной формы.

    Арифметические операции:
        np.add(x, y): Сложение элементов массивов x и y.
        np.subtract(x, y): Вычитание элементов массива y из массива x.
        np.multiply(x, y): Поэлементное умножение массивов x и y.
        np.divide(x, y): Поэлементное деление массива x на массив y.

    Агрегирование данных:
        np.sum(arr): Сумма всех элементов массива arr.
        np.mean(arr): Среднее значение элементов массива arr.
        np.max(arr): Максимальное значение в массиве arr.
        np.min(arr): Минимальное значение в массиве arr.
        np.argmax(arr): Индекс максимального значения в массиве arr.
        np.argmin(arr): Индекс минимального значения в массиве arr.

    Изменение формы массива:
        arr.reshape(new_shape): Изменяет форму массива на заданную.
        arr.flatten(): Преобразует многомерный массив в одномерный.

    Индексация и нарезка:
        arr[index]: Возвращает элемент по индексу.
        arr[start:stop:step]: Выполняет нарезку массива.

    Матричные операции:
        np.dot(a, b): Умножение матриц a и b.
        np.transpose(arr): Транспонирование массива.

    Случайные числа:
        np.random.rand(shape): Генерирует случайные числа с равномерным распределением в заданной форме.

    Фильтрация и маскирование:
        arr > value: Возвращает булев массив, указывающий, какие элементы больше value.
        np.where(condition, x, y): Возвращает элементы из x, если условие condition истинно, и из y в противном случае.

    Сортировка:
        np.sort(arr): Возвращает отсортированный массив.

In [2]:
import numpy as np
import matplotlib.pyplot as plt

### Задание №1

Замените столбец 0 и столбец 1 местами

In [7]:
array = np.arange(9).reshape(3, 3)
print(f"Оригинальный \n{array}")
# Your code:

array[:, [0, 1]] = array[:, [1, 0]]

print(f"Решение \n{array}")

Оригинальный 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Решение 
[[1 0 2]
 [4 3 5]
 [7 6 8]]


### Задание №2

Замените строку 0 и строку 1 местами

In [ ]:
array = np.arange(9).reshape(3, 3)
print(f"Оригинальный \n{array}")
# Your code:

array[[0, 1], :] = array[[1, 0], :]

print(f"Решение \n{array}")

Оригинальный 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Решение 
[[3 4 5]
 [0 1 2]
 [6 7 8]]


### Задание №3

Перепишите цикл перемножения матриц с использованием numpy

In [ ]:
array1 = [*range(1, 10000001)]
array2 = [*range(10, 100000010, 10)]

# Выполняем умножение элементов массивов
def multiply_vectors(array_1, array_2):
    assert len(array_1) == len(array_2)
    return [array_1[i] * array_2[i] for i in range(len(array_1))]

In [ ]:
%%time
result_python = multiply_vectors(array1, array2)

CPU times: user 1.06 s, sys: 282 ms, total: 1.34 s
Wall time: 1.34 s


In [10]:
%%time
# Your code:
array1 = np.arange(1, 10000001)
array2 = np.arange(10, 100000010, 10)

result_python = np.multiply(array1, array2)

CPU times: user 24.3 ms, sys: 95.6 ms, total: 120 ms
Wall time: 177 ms


### Задание №4
Перепишите цикл нахождения факториала с использованием numpy

Подсказка: понадобится ```np.prod()```

In [ ]:
def factorial(n):
    if n == 0:
        return 1
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

In [ ]:
%%time
n_values = [*range(1, 4000)]
for n in n_values:
    result = factorial(n)

CPU times: user 6.03 s, sys: 0 ns, total: 6.03 s
Wall time: 6.15 s


In [11]:
def factorial_numpy(n):
    # Создаем массив от 1 до n
    numbers = np.arange(1, n + 1)

    # Вычисляем факториалы с использованием векторизации NumPy
    # Your code:

    factorials = np.prod(numbers)

    return factorials

In [12]:
%%time
n_values = [*range(1, 4000)]
for n in n_values:
    result = factorial_numpy(n)

CPU times: user 36.1 ms, sys: 0 ns, total: 36.1 ms
Wall time: 36.1 ms


### Задание №5

Расчет общего сопротивления электрической цепи

Вам дан массив $R$ сопротивлений различных элементов электрической цепи, подключенных последовательно.

Ваша задача - вычислить общее сопротивление цепи с использованием функции einsum.

Формула расчета общего сопротивления

$1/R$ = $1/R_1$ + $1/R_2$ + ... + $1/R_n$

In [13]:
resistance_array = np.array([2, 4, 6, 8, 10, 12])

# Your code:

inverse_resistance_sum = np.einsum('i->', 1 / resistance_array)
total_resistance = 1 / inverse_resistance_sum

print(total_resistance)

assert total_resistance == 0.816326530612245

0.816326530612245


### Задание №6

Возведите большой вектор в пятую степень тремя способами с помощью numpy

In [15]:
x = np.random.rand(int(5e7))

In [16]:
%timeit result = x ** 5
%timeit result = np.power(x, 5)
%timeit result = x * x * x * x * x

1.41 s ± 191 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.32 s ± 7.27 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
395 ms ± 24.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
